// One-time script: seeds all locale keys to SiteContent table in Supabase
// Run: node Backend/scripts/seed-content.js  (from project root)
const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

// Parse .env manually
const envPath = path.join(__dirname, '../.env');
const env = Object.fromEntries(
  fs.readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; })
);

const HE = {
  "nav.shop": "חנות",
  "nav.about": "אודות",
  "nav.contact": "צור קשר",
  "nav.adminLogin": "כניסת מנהל",
  "nav.brandSubtitle": "אופנת ג'נודי",
  "home.headline": "מצא את החליפה המושלמת שלך",
  "home.subheadline": "חיפוש מתקדם מבוסס בינה מלאכותית",
  "home.tagline": "אופנת גברים יוקרתית",
  "home.taglineSub": "החליפה הזאת תפורה עלייך",
  "home.bento.collectionTag": "קולקציה",
  "home.bento.collectionTitle": "קולקציית החורף",
  "home.bento.craftTag": "מקצועיות",
  "home.bento.craftTitle": "תפירה אישית",
  "home.bento.craftBody": "כל חליפה נמדדת, נחתכת ומגוהצת בדיוק לפי מידותיך.",
  "home.bento.accessories": "אביזרים",
  "home.experience.tag": "חוויה",
  "home.experience.title": "החוויה של ג'נודי",
  "home.experience.badge1": "בדים יוקרתיים",
  "home.experience.badge2": "מידות אישיות",
  "home.searchPlaceholder": "תאר את החליפה שאתה מחפש (לדוגמה: \"חליפה כחולה לחתונת קיץ\")...",
  "home.imageSearch": "חיפוש לפי תמונה",
  "home.orImageSearch": "או חפש לפי תמונה",
  "home.imageDropTitle": "גרור תמונה לכאן, או לחץ לבחירה",
  "home.imageDropSub": "נמצא פריטים דומים מהמלאי שלנו",
  "home.browseCatalog": "עיין בקטלוג",
  "home.aiComingSoon": "חיפוש AI יהיה זמין בקרוב",
  "home.premiumBadge": "לבוש גברים יוקרתי",
  "home.bentoSectionTitle": "הקולקציה",
  "shop.title": "הקטלוג שלנו",
  "shop.subtitle": "גלו את קולקציית האופנה הגברית שלנו",
  "shop.filters": "סינון",
  "shop.type": "סוג",
  "shop.status": "זמינות",
  "shop.color": "צבע",
  "shop.clearFilters": "נקה סינון",
  "shop.noProducts": "לא נמצאו מוצרים",
  "shop.allTypes": "כל הסוגים",
  "shop.allColors": "כל הצבעים",
  "shop.allStatuses": "כל הסטטוסים",
  "shop.loading": "טוען מוצרים...",
  "shop.error": "שגיאה בטעינת המוצרים",
  "shop.loadMore": "טען עוד",
  "type.JACKET": "ז'קט",
  "type.PANTS": "מכנסיים",
  "type.SHIRT": "חולצה",
  "type.VEST": "וסט",
  "type.SHOES": "נעליים",
  "type.TIE": "עניבה",
  "type.BOW_TIE": "פרפר",
  "type.BELT": "חגורה",
  "status.in_stock": "במלאי",
  "status.out_of_stock": "אזל מהמלאי",
  "product.sku": "קוד מוצר",
  "product.type": "סוג",
  "product.color": "צבע",
  "product.status": "זמינות",
  "product.edit": "עריכה",
  "product.delete": "מחיקה",
  "product.deleteConfirm": "האם אתה בטוח שברצונך למחוק מוצר זה?",
  "product.similar": "פריטים דומים",
  "product.similarNote": "לא נמצאו פריטים דומים",
  "product.noImage": "אין תמונה",
  "product.backToShop": "חזרה לקטלוג",
  "product.notFound": "המוצר לא נמצא",
  "product.readyToShip": "זמין במלאי",
  "product.visitStore": "צור קשר",
  "nav.search": "חיפוש לפי תמונה",
  "search.title": "חיפוש לפי תמונה",
  "search.subtitle": "העלה תמונה של פריט כלשהו ונמצא את הפריטים הדומים ביותר בקולקציה שלנו",
  "search.dropZone": "גרור תמונה לכאן, או לחץ לבחירה",
  "search.dropZoneSub": "JPG, PNG, WEBP — כל תמונה מהרשת או מהטלפון",
  "search.searchBtn": "מצא פריטים דומים",
  "search.searching": "מחפש...",
  "search.resultsFound": "נמצאו {n} תוצאות",
  "search.noResults": "לא נמצאו מוצרים תואמים",
  "search.error": "החיפוש נכשל — אנא נסה שוב",
  "search.detecting": "מנתח תמונה...",
  "search.multipleFound": "זיהינו כמה פריטים בתמונה — איזה פריט לחפש?",
  "search.searchAll": "חפש את כולם",
  "search.showMore": "הצג עוד תוצאות",
  "search.backToPicker": "חזור לבחירת פריט",
  "search.newSearch": "חיפוש חדש",
  "about.title": "אודות אופנת ג'נודי",
  "about.description": "אופנת ג'נודי מתמחה בחליפות גברים איכותיות, ומציעה מגוון רחב של עיצובים לכל אירוע.",
  "about.address": "כתובת",
  "about.phone": "טלפון",
  "about.hours": "שעות פתיחה",
  "about.sun": "ראשון",
  "about.mon": "שני",
  "about.tue": "שלישי",
  "about.wed": "רביעי",
  "about.thu": "חמישי",
  "about.fri": "שישי",
  "about.sat": "שבת",
  "about.closed": "סגור",
  "about.tagline": "אודותינו",
  "about.story.tag": "הסיפור שלנו",
  "about.story.title": "עשרות שנות מצוינות בתפירה",
  "about.story.body": "אופנת ג'נודי, שנוסדה בתל אביב, יוצרת בגדי גברים ברמה גבוהה כבר למעלה משני עשורים. כל פריט משקף את המחויבות שלנו לאיכות, לגזרה המושלמת ולאלגנטיות נצחית.",
  "about.promise.tag": "ההבטחה שלנו",
  "about.promise.title": "תפור עבור הגבר המדקדק",
  "about.promise.body": "אנחנו בוחרים רק את הבדים המשובחים ביותר — צמר Super 150s, פשתן איטלקי ופרטי גימור עשויים ביד — כי אנחנו מאמינים שהיוקרה האמיתית חיה בפרטים הקטנים.",
  "about.visit.tag": "בקרו אותנו",
  "about.visit.title": "בקרו את האטלייה",
  "about.bookAppointment": "קבעו תור",
  "about.hours.tag": "שעות",
  "about.addressLine1": "העלייה 11",
  "about.addressLine2": "תל אביב-יפו 6685803",
  "contact.title": "צור קשר",
  "contact.subtitle": "נשמח לשמוע ממך. השאר פרטים ונחזור אליך בהקדם.",
  "contact.name": "שם מלא",
  "contact.email": "דואר אלקטרוני",
  "contact.message": "הודעה",
  "contact.messagePlaceholder": "כתוב את הודעתך כאן...",
  "contact.send": "שלח במייל",
  "contact.sendWhatsapp": "שלח בווצאפ",
  "contact.sent": "ההודעה נשלחה!",
  "contact.sentNote": "נחזור אליך בהקדם האפשרי.",
  "contact.tagline": "צרו קשר",
  "contact.heroTitle": "נשמח לשמוע מכם",
  "contact.atelierTag": "אטלייה",
  "contact.addressLabel": "כתובת",
  "contact.phoneLabel": "טלפון",
  "contact.emailLabel": "אימייל",
  "contact.hoursLabel": "שעות",
  "contact.hoursSummary": "א׳–ה׳ 10:00–19:00",
  "contact.hoursFri": "ו׳ 10:00–14:30",
  "contact.phone": "מספר טלפון",
  "contact.sending": "שולח...",
  "contact.sendError": "שליחה נכשלה. נסה שוב או צור קשר טלפונית.",
  "admin.dashboard": "לוח בקרה",
  "admin.inventory": "מלאי",
  "admin.inventoryTitle1": "קטלוג",
  "admin.inventoryTitle2": "מוצרים",
  "admin.stockOverview": "סקירת מלאי",
  "admin.uploads": "העלאות",
  "admin.portal": "פורטל מנהל",
  "admin.loginBrand": "אופנת ג׳נודי",
  "admin.backToWebsite": "← חזרה לאתר",
  "admin.sortByName": "שם",
  "admin.sortByDate": "תאריך הוספה",
  "admin.filterType": "סוג",
  "admin.filterColor": "צבע",
  "admin.filterStatus": "סטטוס",
  "admin.noImagesToProcess": "אין תמונות לעיבוד",
  "admin.retryFailed": "נכשל — נסה שנית",
  "admin.processImages": "עבד תמונות עם AI:",
  "admin.selectAll": "בחר הכל",
  "admin.deselectAll": "בטל בחירה",
  "admin.createProduct": "צור מוצר",
  "admin.editProductTitle": "עריכת מוצר",
  "admin.newProductTitle": "מוצר חדש",
  "admin.productFormTitle1": "מוצר",
  "admin.productFormTitleNew": "הוספת",
  "admin.productFormTitleEdit": "עריכת",
  "admin.setAsMain": "הגדר כראשי",
  "admin.removeImage": "הסר",
  "admin.mainImage": "ראשי",
  "admin.pendingUpload": "ממתין להעלאה",
  "admin.greeting": "בוקר טוב, בעל החנות",
  "admin.greetingSub": "הנה מה שקורה בחנות שלך היום",
  "admin.totalProducts": "סה\"כ מוצרים",
  "admin.pendingUploads": "ממתין לעיבוד",
  "admin.agentAlert": "התראת סוכן — פעיל",
  "admin.agentAlertSub": "ניתוח AI זיהה שינויים משמעותיים בשוק",
  "admin.trends": "ניתוח מגמות חיפוש",
  "admin.agentNote": "ניתוח מגמות יהיה פעיל לאחר השלמת אינטגרציית הבינה המלאכותית",
  "admin.addProduct": "הוסף מוצר",
  "admin.editProduct": "עריכת מוצר",
  "admin.saveProduct": "שמור",
  "admin.cancel": "ביטול",
  "admin.productName": "שם בעברית",
  "admin.productNameEn": "שם באנגלית",
  "admin.productNameEnPlaceholder": "אופציונלי",
  "admin.productSku": "קוד מוצר (SKU)",
  "admin.productType": "סוג",
  "admin.productColor": "צבע",
  "admin.productStatus": "סטטוס",
  "admin.imageUpload": "העלאת תמונה",
  "admin.imageDisabled": "העלאת תמונות תהיה זמינה לאחר הגדרת אחסון הענן",
  "admin.deleteConfirm": "האם אתה בטוח שברצונך למחוק מוצר זה?",
  "admin.bulk.selected": "נבחרו",
  "admin.bulk.clear": "נקה",
  "admin.bulk.delete": "מחק",
  "admin.bulk.processBackgrounds": "עבד רקעים",
  "admin.bulk.generateModels": "צור דוגמנים",
  "admin.bulk.inStock": "במלאי",
  "admin.bulk.outOfStock": "אזל מהמלאי",
  "admin.bulk.deleteConfirm": "למחוק {count} מוצרים? לא ניתן לשחזר.",
  "admin.saving": "שומר...",
  "admin.saveSuccess": "המוצר נשמר בהצלחה",
  "admin.saveError": "שגיאה בשמירת המוצר",
  "admin.batchTypeLabel": "סוג מוצר להעלאה",
  "admin.batchTypePlaceholder": "בחר סוג לפני ההעלאה",
  "admin.batchTypeNote": "כל התמונות בהעלאה זו יעובדו כ",
  "admin.batchTypeWarning": "יש לבחור סוג מוצר תחילה — ה-AI משתמש במודל שונה לכל סוג.",
  "admin.uploadTitle": "העלאת מלאי חדש",
  "admin.uploadSub": "עיבוד תמונות אוטומטי מבוסס AI",
  "admin.uploadsTitle1": "העלאת תמונות",
  "admin.uploadsTitle2": "מרובות",
  "admin.selectedLabel": "נבחרו",
  "admin.clearSelection": "נקה",
  "admin.uploading": "מעלה...",
  "admin.dropZoneTitle": "גרור תמונות לכאן או לחץ לעיון",
  "admin.dropZoneFormats": "JPG, PNG, WEBP — כמה שרוצים",
  "admin.dropZoneAi": "הסרת רקע AI מתחיל אוטומטית",
  "admin.imagesAwaitingAssignment": "תמונות ממתינות לשיוך",
  "admin.failed": "נכשל",
  "admin.retry": "נסה שנית",
  "admin.delete": "מחק",
  "admin.noImagesWaiting": "אין תמונות ממתינות לשיוך. העלה תמונות למעלה.",
  "admin.firstImageAsMain": "התמונה הראשונה שנבחרה תוגדר כראשית",
  "admin.dropZone": "גרור תמונות מהטלפון לכאן לעיבוד אוטומטי",
  "admin.dropFeatures": "הסרת רקע  •  תיקון תאורה  •  מרכוז אוטומטי  •  תיקון צבע",
  "admin.uploadComingSoon": "העלאת תמונות תהיה זמינה לאחר הגדרת אחסון הענן",
  "admin.processingQueue": "תור עיבוד",
  "admin.reviewAll": "סקירת הכל",
  "admin.publishCatalog": "פרסם לקטלוג",
  "admin.loginTitle": "כניסת מנהל",
  "admin.loginSub": "גישה לבעלי החנות בלבד",
  "admin.username": "שם משתמש / אימייל",
  "admin.password": "סיסמה",
  "admin.rememberMe": "זכור אותי",
  "admin.forgotPassword": "שכחת סיסמה?",
  "admin.loginBtn": "כניסה מאובטחת",
  "admin.secureNote": "החיבור מוגן עם הצפנה ברמה ארגונית",
  "admin.loginNote": "הגישה מוגבלת לצוות מורשה בלבד",
  "admin.loginError": "אימייל או סיסמה שגויים. אנא נסה שנית.",
  "admin.logout": "התנתקות",
  "insights.title": "תובנות AI",
  "insights.loading": "מנתח נתוני חנות...",
  "insights.error": "לא ניתן לטעון תובנות",
  "insights.retry": "נסה שנית",
  "insights.searchesToday": "חיפושים היום",
  "insights.missingImages": "תמונות חסרות",
  "insights.chatTitle": "שאל את הסוכן",
  "insights.chatPlaceholder": "שאל על מלאי, מגמות...",
  "insights.chatSend": "שלח",
  "insights.chatLoading": "חושב...",
  "insights.chatOpen": "שאל סוכן AI",
  "insights.chatClose": "סגור",
  "footer.company": "חברה",
  "footer.support": "תמיכה",
  "footer.privacyPolicy": "מדיניות פרטיות",
  "footer.joinAtelier": "הצטרפו לאטלייה",
  "footer.joinSub": "הישארו מעודכנים עם הגעות חדשות וקולקציות בלעדיות.",
  "footer.join": "הצטרף",
  "footer.hoursSummary": "א׳–ה׳ 10:00–19:00 · ו׳ 10:00–14:30",
  "footer.copyrightBrand": "אופנת ג'נודי. כל הזכויות שמורות.",
  "footer.addressShort": "העלייה 11, תל אביב",
  "admin.settings": "הגדרות",
  "admin.support": "תמיכה",
  "admin.console": "קונסולת מנהל",
  "admin.searchPlaceholder": "חיפוש...",
  "admin.stockStatus": "מצב מלאי",
  "admin.inStockPct": "במלאי",
  "admin.productItems": "פריטים",
  "admin.productItemsSub": "סה\"כ פריטים בקטלוג, בכל הקטגוריות והסטטוסים.",
  "admin.collectionGrowing": "הקולקציה גדלה",
  "admin.searchesSub": "חיפושי טקסט + תמונה",
  "admin.uploadQueue": "תור העלאה",
  "admin.processed": "עובד",
  "admin.processing": "בעיבוד",
  "admin.viewUploads": "צפה בהעלאות",
  "admin.imagesMissing": "תמונות חסרות",
  "admin.processAll": "עבד הכל",
  "admin.viewProducts": "צפה במוצרים",
  "admin.quickActions": "פעולות מהירות",
  "admin.quickActionsSub": "נהל את הקטלוג שלך",
  "admin.recentActivity": "פעילות אחרונה",
  "admin.last24hrs": "24 שעות אחרונות",
  "admin.trending": "טרנדינג",
  "admin.topProducts": "מוצרים מובילים",
  "admin.topProductsSub": "הנצפים ביותר החודש",
  "admin.viewAll": "צפה בהכל",
  "admin.noProductsWithImages": "אין מוצרים עם תמונות עדיין",
  "admin.aiBusinessAgent": "סוכן עסקי AI",
  "admin.inCatalogue": "בקטלוג",
  "admin.addedToInventory": "נוסף למלאי",
  "admin.statusUpdated": "סטטוס עודכן",
  "admin.catalogueOfStock": "מהקטלוג במלאי",
  "admin.imagesQueued": "תמונות בתור",
  "admin.failedToQueue": "שגיאה בהוספה לתור",
  "admin.colorSearchPlaceholder": "חפש צבע...",
  "admin.products": "מוצרים",
  "admin.sort": "מיון",
  "admin.noProductsFiltered": "לא נמצאו מוצרים התואמים לסינון.",
  "admin.showing": "מציג",
  "admin.of": "מתוך",
  "admin.items": "פריטים",
  "admin.filteredFrom": "מסונן מ-",
  "admin.vto.sectionTitle": "הלבשה על דוגמנים (AI)",
  "admin.vto.frontViewLabel": "תמונת חזית",
  "admin.vto.frontViewHint": "סמן את התמונה הקדמית של הפריט כדי להפעיל את הלבשת הדוגמנים",
  "admin.vto.triggerBtn": "הלבש דוגמנים",
  "admin.vto.running": "מעבד עם AI — עד 3 דקות...",
  "admin.vto.done": "הלבשה הושלמה",
  "admin.vto.failed": "הלבשה נכשלה",
  "admin.vto.selectHint": "בחר אילו דוגמנים להציג באתר",
  "admin.vto.publishBtn": "הוסף לגלריה",
  "admin.vto.publishDone": "התמונות נוספו לגלריה",
  "admin.vto.noFrontView": "יש לסמן תמונת חזית כדי להפעיל את הלבשת הדוגמנים",
  "admin.vto.needProcessed": "יש לעבד את התמונות קודם (הסרת רקע) לפני הלבשת דוגמנים",
  "admin.vto.alreadyRunning": "הלבשה כבר רצה ברקע",
  "admin.vto.retryBtn": "נסה שנית",
  "admin.vto.regenerateBtn": "יצר מחדש",
  "admin.vto.orderHint": "לחץ על תמונה לבחירת הסדר — הראשון יהיה הראשי",
  "admin.vto.deleteResult": "מחק תוצאה",
  "admin.vto.selectModels.title": "בחר דוגמנים",
  "admin.vto.selectModels.subtitle": "בחר על אילו דוגמנים להלביש את הבגד",
  "admin.vto.selectModels.selectAll": "בחר הכל",
  "admin.vto.selectModels.deselectAll": "בטל בחירה",
  "admin.vto.selectModels.confirm": "הפעל VTO",
  "admin.vto.selectModels.noModels": "אין דוגמנים מוגדרים — הוסף תמונות בעמוד הדוגמנים",
  "admin.vto.selectModels.loading": "טוען דוגמנים...",
  "admin.vto.selectModels.photos": "תמונות",
  "admin.saveAndProcess": "שמור וקדם לעיבוד ←",
  "admin.processBackgrounds": "עבד רקעים",
  "admin.processingBackgrounds": "שולח לעיבוד...",
  "admin.processBackgroundsQueued": "תמונות נשלחו לתור עיבוד",
  "admin.processing.sectionTitle": "עיבוד תמונות",
  "admin.processing.unprocessedHint": "יש תמונות שטרם עובדו עם AI",
  "admin.gallery.title": "גלריה",
  "admin.gallery.unpublishBtn": "הסר מהגלריה",
  "admin.gallery.orderHint": "לחץ על תמונות להגדרת סדר תצוגה — ראשון יהיה ראשי",
  "admin.gallery.publishBtn": "פרסם גלריה",
  "admin.gallery.publishDone": "גלריה פורסמה",
  "admin.gallery.empty": "עבד רקעים כדי לראות תמונות כאן",
  "admin.vto.pod.title": "GPU לדוגמנות AI",
  "admin.vto.pod.subtitle": "הפעל את הפוד כדי להלביש ג'קטים/וסטים על דוגמנים",
  "admin.vto.pod.start": "הפעל GPU",
  "admin.vto.pod.stop": "כבה GPU",
  "admin.vto.pod.starting": "מופעל...",
  "admin.vto.pod.stopping": "נכבה...",
  "admin.vto.pod.running": "GPU פעיל",
  "admin.vto.pod.offline": "GPU כבוי",
  "admin.vto.pod.autoStop": "נכבה אוטומטית אחרי שעה",
  "admin.vto.pod.notConfigured": "לא מוגדר",
  "admin.vtoModels.navLabel": "דוגמנים",
  "admin.vtoModels.title": "דוגמני VTO",
  "admin.vtoModels.subtitle": "תמונות הדוגמנים לדוגמנות AI — שינויים יכנסו לתוקף בעבודת VTO הבאה",
  "admin.vtoModels.upload": "העלה תמונות",
  "admin.vtoModels.uploading": "מעלה...",
  "admin.vtoModels.empty": "אין תמונות דוגמנים עדיין",
  "admin.vtoModels.dropHint": "גרור תמונות לכאן, או לחץ על העלה",
  "admin.vtoModels.dropRelease": "שחרר להעלאה",
  "admin.vtoModels.uploadSuccess": "{count} תמונות הועלו",
  "admin.vtoModels.uploadError": "ההעלאה נכשלה",
  "admin.vtoModels.deleteConfirm": "למחוק את תמונת הדוגמן \"{name}\"?",
  "admin.vtoModels.deleteSuccess": "התמונה נמחקה",
  "admin.vtoModels.deleteError": "המחיקה נכשלה",
  "admin.vtoModels.loadError": "טעינת תמונות הדוגמנים נכשלה",
  "admin.vtoModels.photos": "תמונות",
  "admin.vtoModels.addModel": "הוסף דוגמן",
  "admin.vtoModels.newFolderPlaceholder": "שם הדוגמן...",
  "admin.vtoModels.folderExists": "דוגמן עם שם זה כבר קיים",
  "admin.vtoModels.deleteFolderConfirm": "למחוק את הדוגמן \"{name}\" וכל תמונותיו?",
  "admin.vtoModels.renameSuccess": "הדוגמן שונה שם",
  "admin.vtoModels.renameError": "שינוי השם נכשל",
  "admin.content.navLabel": "עריכת תוכן",
  "admin.content.subtitle": "ערוך את הטקסטים בעמודים הציבוריים. שינויים נשמרים מיד לכל המבקרים.",
  "admin.content.colKey": "מפתח",
  "admin.content.colHe": "עברית",
  "admin.content.colEn": "אנגלית",
  "admin.content.save": "שמור",
  "admin.content.saving": "שומר",
  "admin.content.saved": "נשמר",
  "admin.content.replaceImage": "החלף תמונה",
  "admin.content.uploading": "מעלה...",
  "admin.content.uploaded": "הועלה",
  "admin.content.reset": "אפס",
  "admin.content.customImage": "תמונה מותאמת",
  "image.hero-bg": "/placeholders/hero-bg.png",
  "image.bento-collection": "/placeholders/bento-collection.png",
  "image.bento-accessories": "/placeholders/bento-accessories.png",
  "image.experience-1": "/placeholders/experience-1.png",
  "image.experience-2": "/placeholders/experience-2.png",
  "image.about-owner": "/placeholders/about-owner.png",
  "image.store-pic": "/placeholders/store-pic.png",
  "nav.gallery": "גלריה",
  "gallery.tagline": "גלריה",
  "gallery.title": "גלריה",
  "gallery.subtitle": "רגעים מיוחדים עם לבוש אופנת ג'נודי",
  "gallery.loading": "טוען גלריה...",
  "gallery.error": "שגיאה בטעינת הגלריה",
  "gallery.empty": "הגלריה ריקה כרגע — חזרו בקרוב",
  "admin.customerGallery.navLabel": "גלריה",
  "admin.customerGallery.upload": "העלה תמונה",
  "admin.customerGallery.uploading": "מעלה...",
  "admin.customerGallery.captionPlaceholder": "כיתוב (אופציונלי)",
  "admin.customerGallery.dropHint": "גרור תמונה לכאן, או לחץ על העלה תמונה",
  "admin.customerGallery.uploadSuccess": "תמונה הועלתה",
  "admin.customerGallery.uploadError": "ההעלאה נכשלה",
  "admin.customerGallery.deleteConfirm": "למחוק תמונה זו?",
  "admin.customerGallery.deleteSuccess": "התמונה נמחקה",
  "admin.customerGallery.deleteError": "המחיקה נכשלה",
  "admin.customerGallery.empty": "אין תמונות בגלריה עדיין",
  "admin.customerGallery.reorderHint": "השתמש בחצים לשינוי סדר התצוגה",
  "common.loading": "טוען...",
  "common.error": "אירעה שגיאה, נסה שנית",
  "common.back": "חזרה",
  "common.cancel": "ביטול",
  "common.comingSoon": "בקרוב",
  "common.live": "פעיל",
  "addColor.title": "הוסף צבע חדש",
  "addColor.labelHe": "שם בעברית",
  "addColor.placeholderHe": "כחול כהה",
  "addColor.labelEn": "שם באנגלית",
  "addColor.placeholderEn": "Dark Navy",
  "addColor.keyPrefix": "מפתח:",
  "addColor.saving": "שומר...",
  "addColor.submit": "הוסף צבע",
  "addColor.errorSave": "שגיאה בשמירה",
};

const EN = {
  "nav.shop": "Shop",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.adminLogin": "Admin Login",
  "nav.brandSubtitle": "Jenudi Fashion",
  "home.headline": "Find Your Perfect Suit",
  "home.subheadline": "Powered by Advanced AI Search",
  "home.tagline": "Premium Menswear",
  "home.taglineSub": "Tailored For You",
  "home.bento.collectionTag": "Collection",
  "home.bento.collectionTitle": "Winter Collection",
  "home.bento.craftTag": "Craftsmanship",
  "home.bento.craftTitle": "Bespoke Tailoring",
  "home.bento.craftBody": "Every suit is measured, cut, and finished to your exact form.",
  "home.bento.accessories": "Accessories",
  "home.experience.tag": "Experience",
  "home.experience.title": "The Jenudi Experience",
  "home.experience.badge1": "Premium Fabrics",
  "home.experience.badge2": "Custom Measurements",
  "home.searchPlaceholder": "Describe the suit you're looking for (e.g. \"linen beige suit for summer wedding\")...",
  "home.imageSearch": "Search by image",
  "home.orImageSearch": "Or search by image",
  "home.imageDropTitle": "Drag & drop an image, or click to select",
  "home.imageDropSub": "We'll find similar items from our collection",
  "home.browseCatalog": "Browse Catalog",
  "home.aiComingSoon": "AI search coming soon",
  "home.premiumBadge": "PREMIUM MENSWEAR",
  "home.bentoSectionTitle": "The Collection",
  "shop.title": "Our Catalog",
  "shop.subtitle": "Discover our curated menswear collection",
  "shop.filters": "Filters",
  "shop.type": "Type",
  "shop.status": "Availability",
  "shop.color": "Color",
  "shop.clearFilters": "Clear filters",
  "shop.noProducts": "No products found",
  "shop.allTypes": "All types",
  "shop.allColors": "All colors",
  "shop.allStatuses": "All statuses",
  "shop.loading": "Loading products...",
  "shop.error": "Error loading products",
  "shop.loadMore": "Load more",
  "type.JACKET": "Jacket",
  "type.PANTS": "Pants",
  "type.SHIRT": "Shirt",
  "type.VEST": "Vest",
  "type.SHOES": "Shoes",
  "type.TIE": "Tie",
  "type.BOW_TIE": "Bow Tie",
  "type.BELT": "Belt",
  "status.in_stock": "In Stock",
  "status.out_of_stock": "Out of Stock",
  "product.sku": "Product Code",
  "product.type": "Type",
  "product.color": "Color",
  "product.status": "Availability",
  "product.edit": "Edit",
  "product.delete": "Delete",
  "product.deleteConfirm": "Are you sure you want to delete this product?",
  "product.similar": "Similar Items",
  "product.similarNote": "No similar products found.",
  "product.noImage": "No image",
  "product.backToShop": "Back to Catalog",
  "product.notFound": "Product not found",
  "product.readyToShip": "In Stock",
  "product.visitStore": "Contact Us",
  "nav.search": "Search by Image",
  "search.title": "Search by Image",
  "search.subtitle": "Upload a photo of any garment and we'll find the closest matches in our collection",
  "search.dropZone": "Drag & drop an image, or click to browse",
  "search.dropZoneSub": "JPG, PNG, WEBP — any photo from the web or your phone",
  "search.searchBtn": "Find Similar Items",
  "search.searching": "Searching...",
  "search.resultsFound": "{n} results found",
  "search.noResults": "No matching products found",
  "search.error": "Search failed — please try again",
  "search.detecting": "Analyzing image...",
  "search.multipleFound": "We found multiple items — which one do you want to search for?",
  "search.searchAll": "Search all items",
  "search.showMore": "Show more results",
  "search.backToPicker": "Back to item selection",
  "search.newSearch": "New Search",
  "about.title": "About Jenudi Fashion",
  "about.description": "Jenudi Fashion specializes in high-quality men's suits, offering a wide range of styles for every occasion.",
  "about.address": "Address",
  "about.phone": "Phone",
  "about.hours": "Opening Hours",
  "about.sun": "Sunday",
  "about.mon": "Monday",
  "about.tue": "Tuesday",
  "about.wed": "Wednesday",
  "about.thu": "Thursday",
  "about.fri": "Friday",
  "about.sat": "Saturday",
  "about.closed": "Closed",
  "about.tagline": "About Us",
  "about.story.tag": "Our Story",
  "about.story.title": "Decades of Tailoring Excellence",
  "about.story.body": "Established in Tel Aviv, Jenudi Fashion has been crafting premium menswear for over two decades. Every piece reflects our commitment to quality, fit, and timeless elegance.",
  "about.promise.tag": "Our Promise",
  "about.promise.title": "Crafted for the Discerning Man",
  "about.promise.body": "We source only the finest fabrics — Super 150s wool, Italian linens, and hand-finished details — because we believe that true luxury lives in the details.",
  "about.visit.tag": "Visit",
  "about.visit.title": "Visit the Atelier",
  "about.bookAppointment": "Book an Appointment",
  "about.hours.tag": "Hours",
  "about.addressLine1": "Ha'aliyah 11",
  "about.addressLine2": "Tel Aviv-Jaffa 6685803",
  "contact.title": "Contact Us",
  "contact.subtitle": "We'd love to hear from you. Leave your details and we'll get back to you soon.",
  "contact.name": "Full Name",
  "contact.email": "Email Address",
  "contact.message": "Message",
  "contact.messagePlaceholder": "Write your message here...",
  "contact.send": "Send via Email",
  "contact.sendWhatsapp": "Send via WhatsApp",
  "contact.sent": "Message Sent!",
  "contact.sentNote": "We'll get back to you as soon as possible.",
  "contact.tagline": "Reach Out",
  "contact.heroTitle": "Get in Touch",
  "contact.atelierTag": "Atelier",
  "contact.addressLabel": "Address",
  "contact.phoneLabel": "Phone",
  "contact.emailLabel": "Email",
  "contact.hoursLabel": "Hours",
  "contact.hoursSummary": "Sun–Thu 10:00–19:00",
  "contact.hoursFri": "Fri 10:00–14:30",
  "contact.phone": "Phone Number",
  "contact.sending": "Sending...",
  "contact.sendError": "Failed to send. Please try again or contact us by phone.",
  "admin.dashboard": "Dashboard",
  "admin.inventory": "Inventory",
  "admin.inventoryTitle1": "Product",
  "admin.inventoryTitle2": "Catalogue",
  "admin.stockOverview": "Stock Overview",
  "admin.uploads": "Uploads",
  "admin.portal": "Admin Portal",
  "admin.loginBrand": "Jenudi Fashion",
  "admin.backToWebsite": "← Back to website",
  "admin.sortByName": "Name",
  "admin.sortByDate": "Date Added",
  "admin.filterType": "Type",
  "admin.filterColor": "Color",
  "admin.filterStatus": "Status",
  "admin.noImagesToProcess": "No images to process",
  "admin.retryFailed": "Failed — retry",
  "admin.processImages": "Process images with AI:",
  "admin.selectAll": "Select all",
  "admin.deselectAll": "Deselect all",
  "admin.createProduct": "Create Product",
  "admin.editProductTitle": "Edit Product",
  "admin.newProductTitle": "New Product",
  "admin.productFormTitle1": "Product",
  "admin.productFormTitleNew": "Creation",
  "admin.productFormTitleEdit": "Editor",
  "admin.setAsMain": "Set as main",
  "admin.removeImage": "Remove",
  "admin.mainImage": "Main",
  "admin.pendingUpload": "Pending upload",
  "admin.greeting": "Good morning, Store Owner",
  "admin.greetingSub": "Here's what's happening in your store today",
  "admin.totalProducts": "Total Products",
  "admin.pendingUploads": "Pending Processing",
  "admin.agentAlert": "Agent Alert — Live",
  "admin.agentAlertSub": "AI analysis detected significant market shifts",
  "admin.trends": "Search Trend Analysis",
  "admin.agentNote": "Trend analysis will be active after AI integration is complete",
  "admin.addProduct": "Add Product",
  "admin.editProduct": "Edit Product",
  "admin.saveProduct": "Save",
  "admin.cancel": "Cancel",
  "admin.productName": "Hebrew Name",
  "admin.productNameEn": "English Name",
  "admin.productNameEnPlaceholder": "optional",
  "admin.productSku": "Product Code (SKU)",
  "admin.productType": "Type",
  "admin.productColor": "Color",
  "admin.productStatus": "Status",
  "admin.imageUpload": "Upload Image",
  "admin.imageDisabled": "Image upload will be available after cloud storage setup",
  "admin.deleteConfirm": "Are you sure you want to delete this product?",
  "admin.bulk.selected": "selected",
  "admin.bulk.clear": "Clear",
  "admin.bulk.delete": "Delete",
  "admin.bulk.processBackgrounds": "Process backgrounds",
  "admin.bulk.generateModels": "Generate models",
  "admin.bulk.inStock": "In Stock",
  "admin.bulk.outOfStock": "Out of Stock",
  "admin.bulk.deleteConfirm": "Delete {count} products? This cannot be undone.",
  "admin.saving": "Saving...",
  "admin.saveSuccess": "Product saved successfully",
  "admin.saveError": "Error saving product",
  "admin.batchTypeLabel": "Product type for this batch",
  "admin.batchTypePlaceholder": "Select type before uploading",
  "admin.batchTypeNote": "All images in this upload will be processed as",
  "admin.batchTypeWarning": "Select a product type first — the AI uses a different model per type.",
  "admin.uploadTitle": "Upload New Inventory",
  "admin.uploadSub": "AI-powered automated image processing",
  "admin.uploadsTitle1": "Bulk",
  "admin.uploadsTitle2": "Uploads",
  "admin.selectedLabel": "selected",
  "admin.clearSelection": "Clear",
  "admin.uploading": "Uploading...",
  "admin.dropZoneTitle": "Drop images here or click to browse",
  "admin.dropZoneFormats": "JPG, PNG, WEBP — upload as many as you like",
  "admin.dropZoneAi": "AI background removal starts automatically",
  "admin.imagesAwaitingAssignment": "images awaiting assignment",
  "admin.failed": "Failed",
  "admin.retry": "Retry",
  "admin.delete": "Delete",
  "admin.noImagesWaiting": "No images waiting for assignment. Upload some above.",
  "admin.firstImageAsMain": "First selected image will be set as main",
  "admin.dropZone": "Drag raw phone photos here to begin automated processing",
  "admin.dropFeatures": "Background Removal  •  Lighting Enhancement  •  Auto-Centering  •  Color Correction",
  "admin.uploadComingSoon": "Image upload will be available after cloud storage setup",
  "admin.processingQueue": "Processing Queue",
  "admin.reviewAll": "Review All",
  "admin.publishCatalog": "Publish to Catalog",
  "admin.loginTitle": "Admin Login",
  "admin.loginSub": "Store owner access only",
  "admin.username": "Username / Email",
  "admin.password": "Password",
  "admin.rememberMe": "Remember me",
  "admin.forgotPassword": "Forgot password?",
  "admin.loginBtn": "Secure Login",
  "admin.secureNote": "Connection protected with enterprise-grade encryption",
  "admin.loginNote": "Access restricted to authorized personnel only",
  "admin.loginError": "Incorrect email or password. Please try again.",
  "admin.logout": "Logout",
  "insights.title": "AI Insights",
  "insights.loading": "Analyzing store data...",
  "insights.error": "Could not load insights",
  "insights.retry": "Retry",
  "insights.searchesToday": "Searches Today",
  "insights.missingImages": "Missing Images",
  "insights.chatTitle": "Ask the Agent",
  "insights.chatPlaceholder": "Ask about inventory, trends...",
  "insights.chatSend": "Send",
  "insights.chatLoading": "Thinking...",
  "insights.chatOpen": "Ask AI Agent",
  "insights.chatClose": "Close",
  "footer.company": "Company",
  "footer.support": "Support",
  "footer.privacyPolicy": "Privacy Policy",
  "footer.joinAtelier": "Join the Atelier",
  "footer.joinSub": "Stay informed about new arrivals and exclusive collections.",
  "footer.join": "Join",
  "footer.hoursSummary": "Sun–Thu 10:00–19:00 · Fri 10:00–14:30",
  "footer.copyrightBrand": "Jenudi Fashion. All rights reserved.",
  "footer.addressShort": "Ha'aliyah 11, Tel Aviv",
  "admin.settings": "Settings",
  "admin.support": "Support",
  "admin.console": "Admin Console",
  "admin.searchPlaceholder": "Search...",
  "admin.stockStatus": "Stock Status",
  "admin.inStockPct": "in stock",
  "admin.productItems": "Product Items",
  "admin.productItemsSub": "Total items in the product catalogue, across all categories and statuses.",
  "admin.collectionGrowing": "Collection growing",
  "admin.searchesSub": "Text + image searches",
  "admin.uploadQueue": "Upload Queue",
  "admin.processed": "Processed",
  "admin.processing": "Processing",
  "admin.viewUploads": "View uploads",
  "admin.imagesMissing": "images missing",
  "admin.processAll": "Process All",
  "admin.viewProducts": "View products",
  "admin.quickActions": "Quick Actions",
  "admin.quickActionsSub": "Manage your catalogue",
  "admin.recentActivity": "Recent Activity",
  "admin.last24hrs": "Last 24hrs",
  "admin.trending": "Trending",
  "admin.topProducts": "Top Products",
  "admin.topProductsSub": "Most previewed this month",
  "admin.viewAll": "View all",
  "admin.noProductsWithImages": "No products with images yet",
  "admin.aiBusinessAgent": "AI Business Agent",
  "admin.inCatalogue": "in catalogue",
  "admin.addedToInventory": "Added to inventory",
  "admin.statusUpdated": "Status updated",
  "admin.catalogueOfStock": "of catalogue in stock",
  "admin.imagesQueued": "images queued",
  "admin.failedToQueue": "Failed to queue",
  "admin.colorSearchPlaceholder": "Search color...",
  "admin.products": "products",
  "admin.sort": "Sort",
  "admin.noProductsFiltered": "No products match the current filters.",
  "admin.showing": "Showing",
  "admin.of": "of",
  "admin.items": "items",
  "admin.filteredFrom": "filtered from",
  "admin.vto.sectionTitle": "AI Model Try-On",
  "admin.vto.frontViewLabel": "Front view",
  "admin.vto.frontViewHint": "Mark the front-facing image to enable AI model try-on",
  "admin.vto.triggerBtn": "Dress models with AI",
  "admin.vto.running": "Processing with AI — up to 3 minutes...",
  "admin.vto.done": "Try-on complete",
  "admin.vto.failed": "Try-on failed",
  "admin.vto.selectHint": "Select which model photos to show on the website",
  "admin.vto.publishBtn": "Add to gallery",
  "admin.vto.publishDone": "Photos added to gallery",
  "admin.vto.noFrontView": "Mark a front-view image to enable model try-on",
  "admin.vto.needProcessed": "Images must be processed (background removal) before model try-on",
  "admin.vto.alreadyRunning": "Try-on is already running in background",
  "admin.vto.retryBtn": "Retry",
  "admin.vto.regenerateBtn": "Regenerate",
  "admin.vto.orderHint": "Click images to set display order — first selected becomes main",
  "admin.vto.deleteResult": "Delete result",
  "admin.vto.selectModels.title": "Select Models",
  "admin.vto.selectModels.subtitle": "Choose which models to dress with AI",
  "admin.vto.selectModels.selectAll": "Select all",
  "admin.vto.selectModels.deselectAll": "Deselect all",
  "admin.vto.selectModels.confirm": "Run VTO",
  "admin.vto.selectModels.noModels": "No models configured — add photos in the Models page",
  "admin.vto.selectModels.loading": "Loading models...",
  "admin.vto.selectModels.photos": "photos",
  "admin.saveAndProcess": "Save & continue to processing →",
  "admin.processBackgrounds": "Process backgrounds",
  "admin.processingBackgrounds": "Sending to queue...",
  "admin.processBackgroundsQueued": "Images sent to processing queue",
  "admin.processing.sectionTitle": "Image Processing",
  "admin.processing.unprocessedHint": "Some images have not been AI-processed yet",
  "admin.gallery.title": "Gallery",
  "admin.gallery.unpublishBtn": "Remove from gallery",
  "admin.gallery.orderHint": "Click images to set display order — first becomes main",
  "admin.gallery.publishBtn": "Publish gallery",
  "admin.gallery.publishDone": "Gallery published",
  "admin.gallery.empty": "Process backgrounds to see images here",
  "admin.vto.pod.title": "AI Try-On GPU",
  "admin.vto.pod.subtitle": "Start the pod to dress jackets / vests on models",
  "admin.vto.pod.start": "Start GPU",
  "admin.vto.pod.stop": "Stop GPU",
  "admin.vto.pod.starting": "Starting...",
  "admin.vto.pod.stopping": "Stopping...",
  "admin.vto.pod.running": "GPU active",
  "admin.vto.pod.offline": "GPU offline",
  "admin.vto.pod.autoStop": "Auto-stops after 1 hour",
  "admin.vto.pod.notConfigured": "Not configured",
  "admin.vtoModels.navLabel": "Models",
  "admin.vtoModels.title": "VTO Models",
  "admin.vtoModels.subtitle": "Model photos used for AI virtual try-on — changes take effect on the next VTO job",
  "admin.vtoModels.upload": "Upload photos",
  "admin.vtoModels.uploading": "Uploading...",
  "admin.vtoModels.empty": "No model photos yet",
  "admin.vtoModels.dropHint": "Drag & drop photos here, or click Upload",
  "admin.vtoModels.dropRelease": "Drop to upload",
  "admin.vtoModels.uploadSuccess": "{count} photo(s) uploaded",
  "admin.vtoModels.uploadError": "Upload failed",
  "admin.vtoModels.deleteConfirm": "Delete model photo \"{name}\"?",
  "admin.vtoModels.deleteSuccess": "Photo deleted",
  "admin.vtoModels.deleteError": "Delete failed",
  "admin.vtoModels.loadError": "Failed to load model photos",
  "admin.vtoModels.photos": "photos",
  "admin.vtoModels.addModel": "Add model",
  "admin.vtoModels.newFolderPlaceholder": "model name...",
  "admin.vtoModels.folderExists": "A model with this name already exists",
  "admin.vtoModels.deleteFolderConfirm": "Delete model \"{name}\" and all its photos?",
  "admin.vtoModels.renameSuccess": "Model renamed",
  "admin.vtoModels.renameError": "Rename failed",
  "admin.content.navLabel": "Content Editor",
  "admin.content.subtitle": "Edit text across public pages. Changes are saved immediately for all visitors.",
  "admin.content.colKey": "Key",
  "admin.content.colHe": "Hebrew",
  "admin.content.colEn": "English",
  "admin.content.save": "Save",
  "admin.content.saving": "Saving",
  "admin.content.saved": "Saved",
  "admin.content.replaceImage": "Replace image",
  "admin.content.uploading": "Uploading...",
  "admin.content.uploaded": "Uploaded",
  "admin.content.reset": "Reset",
  "admin.content.customImage": "Custom image",
  "image.hero-bg": "/placeholders/hero-bg.png",
  "image.bento-collection": "/placeholders/bento-collection.png",
  "image.bento-accessories": "/placeholders/bento-accessories.png",
  "image.experience-1": "/placeholders/experience-1.png",
  "image.experience-2": "/placeholders/experience-2.png",
  "image.about-owner": "/placeholders/about-owner.png",
  "image.store-pic": "/placeholders/store-pic.png",
  "nav.gallery": "Gallery",
  "gallery.tagline": "Gallery",
  "gallery.title": "Gallery",
  "gallery.subtitle": "Special moments in Jenudi Fashion",
  "gallery.loading": "Loading gallery...",
  "gallery.error": "Error loading gallery",
  "gallery.empty": "The gallery is empty for now — check back soon",
  "admin.customerGallery.navLabel": "Gallery",
  "admin.customerGallery.upload": "Upload Photo",
  "admin.customerGallery.uploading": "Uploading...",
  "admin.customerGallery.captionPlaceholder": "Caption (optional)",
  "admin.customerGallery.dropHint": "Drag a photo here, or click Upload Photo",
  "admin.customerGallery.uploadSuccess": "Photo uploaded",
  "admin.customerGallery.uploadError": "Upload failed",
  "admin.customerGallery.deleteConfirm": "Delete this photo?",
  "admin.customerGallery.deleteSuccess": "Photo deleted",
  "admin.customerGallery.deleteError": "Delete failed",
  "admin.customerGallery.empty": "No photos in the gallery yet",
  "admin.customerGallery.reorderHint": "Use the arrows to change display order",
  "common.loading": "Loading...",
  "common.error": "An error occurred, please try again",
  "common.back": "Back",
  "common.cancel": "Cancel",
  "common.comingSoon": "Coming Soon",
  "common.live": "Live",
  "addColor.title": "Add New Color",
  "addColor.labelHe": "Hebrew Name",
  "addColor.placeholderHe": "כחול כהה",
  "addColor.labelEn": "English Name",
  "addColor.placeholderEn": "Dark Navy",
  "addColor.keyPrefix": "Key:",
  "addColor.saving": "Saving...",
  "addColor.submit": "Add Color",
  "addColor.errorSave": "Failed to save",
};

async function main() {
  // dev-only script: Supabase pooler has intermediate cert issues on Windows
  const pool = new Pool({ connectionString: env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

  const keys = Object.keys(HE);
  console.log(`Seeding ${keys.length} keys to SiteContent...`);

  const client = await pool.connect();
  try {
    for (const key of keys) {
      const he = HE[key];
      const en = EN[key] ?? he;
      await client.query(
        `INSERT INTO "SiteContent" (key, he, en, "updatedAt")
         VALUES ($1, $2, $3, NOW())
         ON CONFLICT (key) DO UPDATE SET he = $2, en = $3, "updatedAt" = NOW()`,
        [key, he, en]
      );
    }
    console.log(`Done. ${keys.length} keys seeded.`);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch(err => { console.error(err); process.exit(1); });
